language: node_js

script:
  - npm --version

deploy:
  provider: firebase
  token:
    secure: vNe/i8sVdH2KZRbhygGyR5sRLzKIgMgkhqa/Zi5AJd+/+nTsLhrJJgXlS75gnK5/uHZdLTwXTUCsPHxH6K4xgRMTGXW/BU5mqADkNSDI2sy/ud8NaiQrWDZcpjTh3+peFxina6nvqWyuM5wG4skISm0mGIe6rjEUXniFb3teGvMkhFZgeX1q0dA+OMHvz3mwcVb4xFrWQG13etZ3oqV6994y3BWb8FgcotJnfvnA6Mg6JbLRGrM8YjVLQVdMcfL2/nFjoORJO5D3SZaELtISr1STA2Pq0+zPXHw5ykOYx33IDUiQmc2v1Mz21kaO1UY0PtCs71OmvaLWFumv8vY2BIvmx8zjf/b0wYHp+wOC2PQ3Ie1p4IPqRd0oNK2H/Z483YarKfSZsPuhmBZXHcSR8d6+U4DNTekQ/WskeGkGjGdBJ7d5jz7ETFNefqmRJ5iDbHid0sdM19MObELR5fF/r4YozNDyA57F8d+BbwGuRxIJ0xbvb2CsbRaQJjMJXAh7X6sIHnxFzRwmFvpevlXdsNicr3FcjGNaDCYuSGKnN8dqQrWNTR+FWVpafv3Akg8l5Q6FVoWedrBNubwg6nAJ9qMqQMoiIAVcLHorKgyDCAn6h3xuhukzailQpTOzB4T0+vM6H639fQxCkwbC70mrKgpS12EhtG1KzYaZWjvKYNY=

notifications:
  slack:
    rooms:
      secure: U5i5xZpKuQTwm0AoZJF7C33mXbbWKsR92OMwHsTswlQ/JMUtQvhol+DJO90Mk/RVJfWMs0h6/9bIoG8fGUg03qMr76vGYQOVvR0pQfMPILJwYyzcYNwP5SUAcZ61n3BE2Rv/WfFzvFdVQ5fVfn3q1tGmFR5XhyuDsoIi0i6NjDUJrjW9XmnPx/KqAjUfn+EVv7mRQ0HtpsalkpQ8NS0OnvUgBDqGcf8VT7lewq8WvhKuZDXvNK4jMDp+MdfHqQkun+uJcDegpCNj/csqxe8xP0M2CxbR0MQeb6PRtyFd6AH8dxIEsYZqXx5Bppu8YKwN9lQUj/rKYi/IUyw/v8CscOZIepNehz+5R/rR+udZ4YnM7VN1fIdrnq3ojk2c43+gJ8/p+h7JClMsNOl1Cof63AwbzvxbpCOUu3kfwXhV5qrqj92YPL+6TbCSRx42sDeIN9rJa2VN1uXKuAewG44f7X9wbhegHmslomWRMb0mpq7v6nT4Tf6bhAG5tnDy9g8bXDDd/e7aURykOIlfYMJrf9sI8tdH+3Zl8c1/UHYrE4Pl60PAwnJQ+DTZjmtk/6N2XfuFw1WWtSIjCoFKGbg57jE/9u4GCwaTcU9oE3nlgaZnQVmRHm37iIJ4yc9FfElA014ciTHwpgBmPqyse9VEIkJND1QEk7XusInSSDcrDXA=

